# config context path to "/" by setting an empty string
server:
  contextPath:
  port: 9090

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  header: Authorization
  secret: mySecret
#  expiration: 604800
  expiration: 3600
  route:
    authentication:
      path: auth
      refresh: refresh

#logging:
#  level:
#    org.springframework:
#      security: DEBUG